# Generated by Django 4.2.7 on 2025-03-28 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0001_initial'),
        ('academia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instrutor'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.turma', verbose_name='Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('data', 'aluno_presente', 'turma')},
        ),
    ]
