# Generated by Django 4.2.7 on 2025-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_aula_delete_frequencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.RemoveField(
            model_name='aula',
            name='instrutor',
        ),
    ]
