# Generated by Django 4.2.7 on 2025-04-08 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_aluno_contato_alter_aluno_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0006_alter_aula_unique_together_aula_instrutor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['-data'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aula',
            name='alunos_presentes',
            field=models.ManyToManyField(to='academia.aluno', verbose_name='Alunos Presentes'),
        ),
        migrations.AddField(
            model_name='aula',
            name='instrutores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Instrutores'),
        ),
        migrations.RemoveField(
            model_name='aula',
            name='aluno_presente',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='instrutor',
        ),
    ]
