# Generated by Django 4.2.7 on 2025-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('contato', models.CharField(max_length=20, verbose_name='Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(choices=[('0', 'Branca'), ('1', 'Cinza/Branca'), ('2', 'Cinza'), ('3', 'Cinza/Preta'), ('4', 'Amarela/Branca'), ('5', 'Amarela'), ('6', 'Amarela/Preta'), ('7', 'Laranja/Branca'), ('8', 'Laranja'), ('9', 'Laranja/Preta'), ('10', 'Verde/Branca'), ('11', 'Verde'), ('12', 'Verde/Preta'), ('13', 'Azul'), ('14', 'Roxa'), ('15', 'Marrom'), ('16', 'Preta'), ('17', 'Vermelha/Preta'), ('18', 'Vermelha/Branca'), ('19', 'Vermelha')], unique=True, verbose_name='max_length=2')),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Graduações',
                'ordering': ['faixa'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Turma')),
                ('dias_da_semana', models.CharField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, verbose_name='Dias da Semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
