# Generated by Django 4.2.7 on 2025-03-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='Instrutor',
        ),
    ]
