# Generated by Django 4.2.7 on 2025-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_remove_turma_instrutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='turma',
            name='dias_da_semana',
        ),
        migrations.AddField(
            model_name='turma',
            name='dias_da_semana',
            field=models.ManyToManyField(to='academia.diasemana', verbose_name='Dias da Semana'),
        ),
    ]
