# Generated by Django 4.2.7 on 2025-03-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_diasemana_remove_turma_dias_da_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasemana',
            name='dia',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='faixa',
            field=models.CharField(choices=[('0', 'Branca'), ('1', 'Cinza/Branca'), ('2', 'Cinza'), ('3', 'Cinza/Preta'), ('4', 'Amarela/Branca'), ('5', 'Amarela'), ('6', 'Amarela/Preta'), ('7', 'Laranja/Branca'), ('8', 'Laranja'), ('9', 'Laranja/Preta'), ('10', 'Verde/Branca'), ('11', 'Verde'), ('12', 'Verde/Preta'), ('13', 'Azul'), ('14', 'Roxa'), ('15', 'Marrom'), ('16', 'Preta'), ('17', 'Vermelha/Preta'), ('18', 'Vermelha/Branca'), ('19', 'Vermelha')], max_length=2, unique=True),
        ),
    ]
