# Generated by Django 4.2.7 on 2025-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_diasemana_dia_alter_graduacao_faixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='faixa',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dias_da_semana',
            field=models.ManyToManyField(to='academia.diasemana'),
        ),
    ]
