# Generated by Django 4.2.7 on 2025-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_graduacao_faixa_alter_turma_dias_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dias_da_semana',
            field=models.ManyToManyField(blank=True, to='academia.diasemana'),
        ),
    ]
