# Generated by Django 4.2.7 on 2026-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_aluno_contato_alter_aluno_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='graus',
            field=models.IntegerField(default=0, verbose_name='Graus'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável'),
        ),
    ]
