# Generated by Django 4.2.7 on 2026-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_aluno_graus_aluno_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_graduacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Graduação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_grau',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Grau'),
        ),
    ]
