# Generated by Django 4.2.7 on 2026-01-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_aluno_data_graduacao_aluno_data_grau'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Convite de Aluno',
                'verbose_name_plural': 'Convites de Alunos',
                'ordering': ['-created_at'],
            },
        ),
    ]
