# Generated by Django 4.2.7 on 2025-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instrutores/', verbose_name='Foto'),
        ),
    ]
