# Generated by Django 4.2.7 on 2025-04-03 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_instrutor_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='instrutor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='instrutor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='instrutor',
            name='email_confirmado',
        ),
        migrations.RemoveField(
            model_name='instrutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instrutor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='instrutor',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrutor',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
